version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.2.0

executors:
  default:
    docker:
      - image: "cimg/node:23.9.0"
    environment:
      AWS_REGION: "us-west-2"

jobs:
  build:
    executor: "default"
    steps:
      - run:
          name: "Debug OIDC Token"
          command: |
            if [ -n "${CIRCLE_OIDC_TOKEN}" ]; then
              echo "OIDC token exists."
              echo "${CIRCLE_OIDC_TOKEN}" | cut -c1-50  # Print only the first 50 characters for debugging
            else
              echo "OIDC token is not available."
            fi
      - run:
          name: "Inspect OIDC Token"
          command: |
            echo "${CIRCLE_OIDC_TOKEN}" | cut -d "." -f2 | base64 --decode | jq .

      - aws-cli/setup:
          role_arn: "${AWS_ROLE_ARN}"
          role_session_name: "${AWS_ROLE_SESSION_NAME}"

      - checkout

      - run:
          name: "Install Lambda Packages"
          command: |
            cd lambda/authorizer && npm install
            cd ../../
            cd lambda/processJob && npm install
            cd ../../

      - run:
          name: "Build Project"
          command: |
            npm install
            npm run build

      - run:
          name: "CDK Diff"
          command: |
            if [ -n "$CIRCLE_PULL_REQUEST" ]; then
              export ENV=stg
              if [ "${CIRCLE_BRANCH}" == "develop" ]; then
                export ENV=prd
              fi 
              pr_number=${CIRCLE_PULL_REQUEST##*/}
              block='```'
              diff=$(echo -e "cdk diff (env=${ENV})\n${block}\n$(npm run --silent ci_diff)\n${block}")
              data=$(jq -n --arg body "$diff" '{ body: $body }') # escape
              curl -X POST -H 'Content-Type:application/json' \
                -H 'Accept: application/vnd.github.v3+json' \
                -H "Authorization: token ${GITHUB_TOKEN}" \
                -d "$data" \
                "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/issues/${pr_number}/comments"
            fi

      - run:
          name: "CDK Deploy"
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              ENV=prd npm run ci_deploy
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              ENV=stg npm run ci_deploy
            fi
